// <auto-generated />
using System;
using FinanceManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceManager.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceManagerDbContext))]
    [Migration("20260430135802_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FinanceManager.Domain.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.BankRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInternalTransfer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("BankRecords");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.BudgetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetYearId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopePosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetYearId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BudgetEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aa80d28-32f0-eeef-bce0-b75c8342e1ad"),
                            Amount = 4564.85m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("edde9471-7608-76af-dcf9-559581f8a684"),
                            Length = 12,
                            ScopePosition = 0
                        },
                        new
                        {
                            Id = new Guid("98f9cfbc-5c58-b7a8-a508-937de00706c7"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("a4bf5c0d-95de-99a1-21d5-57439d215eee"),
                            Length = 8,
                            ScopePosition = 2
                        },
                        new
                        {
                            Id = new Guid("b0de3032-d308-49fe-ff7f-efcbc925a3c5"),
                            Amount = 100m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("59a2c369-e974-67c7-d335-b3f9786ba939"),
                            Length = 12,
                            ScopePosition = 0
                        },
                        new
                        {
                            Id = new Guid("65a84c8b-151b-f58e-429a-fac0ded1d207"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 0
                        },
                        new
                        {
                            Id = new Guid("eeda34ee-9dcd-b6ea-1e24-619f98e5276c"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 1
                        },
                        new
                        {
                            Id = new Guid("9c8ffde0-85ce-e65f-24a3-c4dd504d5e23"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 2
                        },
                        new
                        {
                            Id = new Guid("fb406164-3442-2097-e9c0-f92167139ce6"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 3
                        },
                        new
                        {
                            Id = new Guid("f9048b38-24f4-54c4-3b53-6ea1be7a42ba"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 4
                        },
                        new
                        {
                            Id = new Guid("f3475e30-0f20-6ccb-e1bb-7c0e570e8b6a"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 5
                        },
                        new
                        {
                            Id = new Guid("f72da5a7-11d7-2579-9576-db25276f548d"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 6
                        },
                        new
                        {
                            Id = new Guid("f1876e3c-76b0-944f-3491-a439f25bd493"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 7
                        },
                        new
                        {
                            Id = new Guid("8aceb345-e684-1569-9e20-71d352267586"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 8
                        },
                        new
                        {
                            Id = new Guid("431638db-b408-e7e3-9f8a-55c8f1337287"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 9
                        },
                        new
                        {
                            Id = new Guid("9f80f866-e242-df06-bf87-da99cb8da175"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 10
                        },
                        new
                        {
                            Id = new Guid("e8d71a02-ee25-2f07-9d3c-18784939719c"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 11
                        },
                        new
                        {
                            Id = new Guid("cad01ba1-c8d0-07b6-66c3-dff0ee8dfbdf"),
                            Amount = 50m,
                            BudgetYearId = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            CategoryId = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Length = 0,
                            ScopePosition = 12
                        },
                        new
                        {
                            Id = new Guid("5573a051-0da2-9490-f3cc-f8e3166cc49c"),
                            Amount = 50m,
                            BudgetYearId = new Guid("6f8a9e01-2428-ebf5-2bb8-6a6e68ffbae3"),
                            CategoryId = new Guid("a4bf5c0d-95de-99a1-21d5-57439d215eee"),
                            Length = 24,
                            ScopePosition = 0
                        },
                        new
                        {
                            Id = new Guid("11177dae-9d42-ac52-be04-f9fb49f998fc"),
                            Amount = 100m,
                            BudgetYearId = new Guid("6f8a9e01-2428-ebf5-2bb8-6a6e68ffbae3"),
                            CategoryId = new Guid("59a2c369-e974-67c7-d335-b3f9786ba939"),
                            Length = 20,
                            ScopePosition = 2
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.BudgetYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BudgetYears");

                    b.HasData(
                        new
                        {
                            Id = new Guid("071e6505-028e-67b8-a567-5e6a78f1441e"),
                            Scope = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("6f8a9e01-2428-ebf5-2bb8-6a6e68ffbae3"),
                            Scope = 1,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("0c07d10a-dc11-ed59-4c90-753a73437fcb"),
                            Scope = 2,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edde9471-7608-76af-dcf9-559581f8a684"),
                            Colour = "#54478C",
                            GroupId = new Guid("41fd5a96-dfa1-c346-f200-615f1e3819da"),
                            Name = "Salary"
                        },
                        new
                        {
                            Id = new Guid("ee9dba81-9029-42f1-b299-2558dc5c433f"),
                            Colour = "#54478C",
                            GroupId = new Guid("41fd5a96-dfa1-c346-f200-615f1e3819da"),
                            Name = "Freelance"
                        },
                        new
                        {
                            Id = new Guid("6deea436-dfed-9b89-89ed-9e6928881a76"),
                            Colour = "#54478C",
                            GroupId = new Guid("41fd5a96-dfa1-c346-f200-615f1e3819da"),
                            Name = "Bonus"
                        },
                        new
                        {
                            Id = new Guid("df78a32b-c7f1-49ef-3d51-9107a38022b7"),
                            Colour = "#2C699A",
                            GroupId = new Guid("da8eb203-45f4-4246-be7a-32400f28af7f"),
                            Name = "Dividends"
                        },
                        new
                        {
                            Id = new Guid("c93898d9-4345-1397-e986-f690aacedee7"),
                            Colour = "#2C699A",
                            GroupId = new Guid("da8eb203-45f4-4246-be7a-32400f28af7f"),
                            Name = "Interest"
                        },
                        new
                        {
                            Id = new Guid("9519dc36-b632-2177-c506-4a9bad98aa42"),
                            Colour = "#2C699A",
                            GroupId = new Guid("da8eb203-45f4-4246-be7a-32400f28af7f"),
                            Name = "Rental Income"
                        },
                        new
                        {
                            Id = new Guid("0bcf2a54-f685-7120-acee-a233d4b6a1f7"),
                            Colour = "#048BA8",
                            GroupId = new Guid("a9499028-0ca8-09d8-c76b-b123fd5389c3"),
                            Name = "Allowance"
                        },
                        new
                        {
                            Id = new Guid("5dfae572-c2b6-48bb-8d04-ad97b5390701"),
                            Colour = "#048BA8",
                            GroupId = new Guid("a9499028-0ca8-09d8-c76b-b123fd5389c3"),
                            Name = "Unemployment"
                        },
                        new
                        {
                            Id = new Guid("704f1753-ddab-ef32-ddfc-6d7c845afee6"),
                            Colour = "#048BA8",
                            GroupId = new Guid("a9499028-0ca8-09d8-c76b-b123fd5389c3"),
                            Name = "Pension"
                        },
                        new
                        {
                            Id = new Guid("47919a35-a424-d01a-27a4-71c0d5bddfa8"),
                            Colour = "#0DB39E",
                            GroupId = new Guid("b4d9e2bd-f6ce-aaa3-f088-5db86b4b2c84"),
                            Name = "Medical Services"
                        },
                        new
                        {
                            Id = new Guid("4fc43ea6-b1a9-bd2a-4b65-aeae8820b99e"),
                            Colour = "#0DB39E",
                            GroupId = new Guid("b4d9e2bd-f6ce-aaa3-f088-5db86b4b2c84"),
                            Name = "Medication"
                        },
                        new
                        {
                            Id = new Guid("79aa7f1d-79b2-ee78-2d75-22de74b4f1da"),
                            Colour = "#0DB39E",
                            GroupId = new Guid("b4d9e2bd-f6ce-aaa3-f088-5db86b4b2c84"),
                            Name = "Supplements"
                        },
                        new
                        {
                            Id = new Guid("a4bf5c0d-95de-99a1-21d5-57439d215eee"),
                            Colour = "#0DB39E",
                            GroupId = new Guid("b4d9e2bd-f6ce-aaa3-f088-5db86b4b2c84"),
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = new Guid("cb94032d-63ea-9a90-5828-869a0dce0938"),
                            Colour = "#0DB39E",
                            GroupId = new Guid("b4d9e2bd-f6ce-aaa3-f088-5db86b4b2c84"),
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = new Guid("71aece19-9360-1fac-494e-f9205f50179c"),
                            Colour = "#0DB39E",
                            GroupId = new Guid("b4d9e2bd-f6ce-aaa3-f088-5db86b4b2c84"),
                            Name = "Ambulance Cover"
                        },
                        new
                        {
                            Id = new Guid("78d04929-9683-26a2-e2df-ad7f359665c9"),
                            Colour = "#EFEA5A",
                            GroupId = new Guid("d7f03733-edcb-08d6-7c42-058ddf10c22e"),
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("1c068252-c4fb-42b0-2bc3-83a56d30049c"),
                            Colour = "#EFEA5A",
                            GroupId = new Guid("d7f03733-edcb-08d6-7c42-058ddf10c22e"),
                            Name = "Activities"
                        },
                        new
                        {
                            Id = new Guid("fde256b0-0e08-12cb-43c4-7ad85ef80976"),
                            Colour = "#EFEA5A",
                            GroupId = new Guid("d7f03733-edcb-08d6-7c42-058ddf10c22e"),
                            Name = "Alcohol"
                        },
                        new
                        {
                            Id = new Guid("d045dbb5-c5ba-aec9-236a-a16e9c041d17"),
                            Colour = "#EFEA5A",
                            GroupId = new Guid("d7f03733-edcb-08d6-7c42-058ddf10c22e"),
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("ca2e2ad8-d0e5-f55a-bb28-651feb824a97"),
                            Colour = "#F29E4C",
                            GroupId = new Guid("f9c4d5cf-ef6e-bb5a-c7ed-73bfe297e22d"),
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("af5d67de-3557-0a99-9592-ac0df06c47ff"),
                            Colour = "#F29E4C",
                            GroupId = new Guid("f9c4d5cf-ef6e-bb5a-c7ed-73bfe297e22d"),
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("86dc2c35-a408-b39a-4af5-5f51084dde46"),
                            Colour = "#F29E4C",
                            GroupId = new Guid("f9c4d5cf-ef6e-bb5a-c7ed-73bfe297e22d"),
                            Name = "Gas"
                        },
                        new
                        {
                            Id = new Guid("4ba174b2-3014-fcc3-35f6-86e96db9d648"),
                            Colour = "#F29E4C",
                            GroupId = new Guid("f9c4d5cf-ef6e-bb5a-c7ed-73bfe297e22d"),
                            Name = "Internet"
                        },
                        new
                        {
                            Id = new Guid("8b0689a8-1fba-72a6-f92b-afe39f6a6488"),
                            Colour = "#F29E4C",
                            GroupId = new Guid("f9c4d5cf-ef6e-bb5a-c7ed-73bfe297e22d"),
                            Name = "Phone"
                        },
                        new
                        {
                            Id = new Guid("c22dccb9-624f-b91c-75f7-e5d7d979ef6e"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Public Transport"
                        },
                        new
                        {
                            Id = new Guid("3193562e-275e-0850-31b4-974eff007b73"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = new Guid("4a75b957-8f25-a61c-8dd5-35dd01fff8c1"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = new Guid("3203c998-b0d1-930e-14d9-643d0a8b013a"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Taxi"
                        },
                        new
                        {
                            Id = new Guid("99c42f85-be8d-816e-83d4-066daae18dc7"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Fees"
                        },
                        new
                        {
                            Id = new Guid("92110c82-632c-8b70-4ca6-b854abf886cc"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Registration"
                        },
                        new
                        {
                            Id = new Guid("7b11f8f1-148c-9205-6970-4d08f603ea23"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = new Guid("832dc26e-7be4-5e67-aa2c-c8153a3aaeee"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Roadside Assistance"
                        },
                        new
                        {
                            Id = new Guid("dcda26d0-a7a3-2196-2b57-9dffa9195e6d"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Flights"
                        },
                        new
                        {
                            Id = new Guid("dfd15343-dfc7-f1b4-8a16-ec37f108f71d"),
                            Colour = "#F1C453",
                            GroupId = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Name = "Car Hire"
                        },
                        new
                        {
                            Id = new Guid("6e7d0a5c-8711-75b0-5588-f8b580359994"),
                            Colour = "#2C699A",
                            GroupId = new Guid("f6877abd-9e18-6cd8-d879-a8765e15f922"),
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("59a2c369-e974-67c7-d335-b3f9786ba939"),
                            Colour = "#2C699A",
                            GroupId = new Guid("f6877abd-9e18-6cd8-d879-a8765e15f922"),
                            Name = "Dining Out"
                        },
                        new
                        {
                            Id = new Guid("41c98146-4c8a-c63a-8209-e939ca0ce622"),
                            Colour = "#2C699A",
                            GroupId = new Guid("f6877abd-9e18-6cd8-d879-a8765e15f922"),
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = new Guid("7fdcc34a-438b-0e1d-39ac-2e2fd423267e"),
                            Colour = "#83E377",
                            GroupId = new Guid("c62f0785-cd46-1598-f91f-96cd5b0c2000"),
                            Name = "EFTs"
                        },
                        new
                        {
                            Id = new Guid("9b3c6308-2439-31e5-edae-9bf1bfbf1b37"),
                            Colour = "#83E377",
                            GroupId = new Guid("c62f0785-cd46-1598-f91f-96cd5b0c2000"),
                            Name = "Stocks"
                        },
                        new
                        {
                            Id = new Guid("1cb76f90-ef3c-f911-c056-6c119ba798f6"),
                            Colour = "#83E377",
                            GroupId = new Guid("c62f0785-cd46-1598-f91f-96cd5b0c2000"),
                            Name = "Real Estate"
                        },
                        new
                        {
                            Id = new Guid("39577e80-5652-74b3-2673-bf85e294c464"),
                            Colour = "#83E377",
                            GroupId = new Guid("c62f0785-cd46-1598-f91f-96cd5b0c2000"),
                            Name = "Superannuation"
                        },
                        new
                        {
                            Id = new Guid("e5187a8b-5cb7-2bb6-d389-55f5b8002b80"),
                            Colour = "#16DB93",
                            GroupId = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Name = "Mortgage"
                        },
                        new
                        {
                            Id = new Guid("762c574f-9032-6e8e-5523-2cb247e4fc79"),
                            Colour = "#16DB93",
                            GroupId = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Name = "Rent"
                        },
                        new
                        {
                            Id = new Guid("e21db71e-33ec-61b5-2932-fd1529589078"),
                            Colour = "#16DB93",
                            GroupId = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Name = "Rates & Taxes"
                        },
                        new
                        {
                            Id = new Guid("dae31b3d-738a-f7e4-7133-36652f437f44"),
                            Colour = "#16DB93",
                            GroupId = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = new Guid("43095cea-c7a8-ad7c-dfb7-d44c289a1df2"),
                            Colour = "#16DB93",
                            GroupId = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("4dd6c9d0-546e-ba8d-aed4-778239f3fa1f"),
                            Colour = "#16DB93",
                            GroupId = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = new Guid("7617c09c-6e50-58e3-8d0d-90a1eba13580"),
                            Colour = "#16DB93",
                            GroupId = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Name = "Accommodation"
                        },
                        new
                        {
                            Id = new Guid("91ac66cd-33d2-eb83-613f-11fe0fdeb741"),
                            Colour = "#B9E769",
                            GroupId = new Guid("cbc8ceb8-bffb-28b0-9521-16dd5365e763"),
                            Name = "Hygiene"
                        },
                        new
                        {
                            Id = new Guid("b97d8891-3fd2-2d51-a300-bd3822a9df13"),
                            Colour = "#B9E769",
                            GroupId = new Guid("cbc8ceb8-bffb-28b0-9521-16dd5365e763"),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("54a2a109-285a-dbee-40a5-861c9aac1700"),
                            Colour = "#B9E769",
                            GroupId = new Guid("cbc8ceb8-bffb-28b0-9521-16dd5365e763"),
                            Name = "Cosmetics"
                        },
                        new
                        {
                            Id = new Guid("2a02555c-eedb-63b8-6bf7-31cb7881eae3"),
                            Colour = "#B9E769",
                            GroupId = new Guid("cbc8ceb8-bffb-28b0-9521-16dd5365e763"),
                            Name = "Grooming"
                        },
                        new
                        {
                            Id = new Guid("19c8c320-7676-8b16-b987-7270ce133291"),
                            Colour = "#B9E769",
                            GroupId = new Guid("cbc8ceb8-bffb-28b0-9521-16dd5365e763"),
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = new Guid("1f56ce83-31c8-a1b4-ccc9-91b871a862d8"),
                            Colour = "#B9E769",
                            GroupId = new Guid("cbc8ceb8-bffb-28b0-9521-16dd5365e763"),
                            Name = "Tuition"
                        },
                        new
                        {
                            Id = new Guid("52f17db3-796d-f82d-474f-f235393b52a8"),
                            Colour = "#54478C",
                            GroupId = new Guid("1646550e-6916-1079-ba01-e5cec7235b7c"),
                            Name = "Bank Fees"
                        },
                        new
                        {
                            Id = new Guid("865c5185-1ab0-17bb-d45d-71c79518fa47"),
                            Colour = "#54478C",
                            GroupId = new Guid("1646550e-6916-1079-ba01-e5cec7235b7c"),
                            Name = "Credit Card Fees"
                        },
                        new
                        {
                            Id = new Guid("ee1f4402-9744-4180-4056-5ac90335edd6"),
                            Colour = "#54478C",
                            GroupId = new Guid("1646550e-6916-1079-ba01-e5cec7235b7c"),
                            Name = "Accountant"
                        },
                        new
                        {
                            Id = new Guid("b15edf39-0ccc-a4f2-52a7-d7d290b7c74e"),
                            Colour = "#048BA8",
                            GroupId = new Guid("1e1b0eec-efff-7720-dec2-be6f86e2218d"),
                            Name = "Presents"
                        },
                        new
                        {
                            Id = new Guid("93a7d7ae-f9ba-6095-00e3-af69eb0b1af0"),
                            Colour = "#048BA8",
                            GroupId = new Guid("1e1b0eec-efff-7720-dec2-be6f86e2218d"),
                            Name = "Charity"
                        },
                        new
                        {
                            Id = new Guid("ba630310-8509-65fe-aa89-57586fd4ba87"),
                            Colour = "#048BA8",
                            GroupId = new Guid("1e1b0eec-efff-7720-dec2-be6f86e2218d"),
                            Name = "Donations"
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.CategoryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41fd5a96-dfa1-c346-f200-615f1e3819da"),
                            Colour = "#54478C",
                            IsIncome = true,
                            Name = "Employment"
                        },
                        new
                        {
                            Id = new Guid("da8eb203-45f4-4246-be7a-32400f28af7f"),
                            Colour = "#2C699A",
                            IsIncome = true,
                            Name = "Investment"
                        },
                        new
                        {
                            Id = new Guid("a9499028-0ca8-09d8-c76b-b123fd5389c3"),
                            Colour = "#048BA8",
                            IsIncome = true,
                            Name = "Support"
                        },
                        new
                        {
                            Id = new Guid("1646550e-6916-1079-ba01-e5cec7235b7c"),
                            Colour = "#54478C",
                            IsIncome = false,
                            Name = "Financial"
                        },
                        new
                        {
                            Id = new Guid("f6877abd-9e18-6cd8-d879-a8765e15f922"),
                            Colour = "#2C699A",
                            IsIncome = false,
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("1e1b0eec-efff-7720-dec2-be6f86e2218d"),
                            Colour = "#048BA8",
                            IsIncome = false,
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = new Guid("b4d9e2bd-f6ce-aaa3-f088-5db86b4b2c84"),
                            Colour = "#0DB39E",
                            IsIncome = false,
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("35996ab8-0fdc-3e69-07d3-038cf34b013d"),
                            Colour = "#16DB93",
                            IsIncome = false,
                            Name = "Housing"
                        },
                        new
                        {
                            Id = new Guid("c62f0785-cd46-1598-f91f-96cd5b0c2000"),
                            Colour = "#83E377",
                            IsIncome = false,
                            Name = "Investing"
                        },
                        new
                        {
                            Id = new Guid("cbc8ceb8-bffb-28b0-9521-16dd5365e763"),
                            Colour = "#B9E769",
                            IsIncome = false,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = new Guid("d7f03733-edcb-08d6-7c42-058ddf10c22e"),
                            Colour = "#EFEA5A",
                            IsIncome = false,
                            Name = "Recreation"
                        },
                        new
                        {
                            Id = new Guid("73cde36e-333b-716c-07cd-2034ff341b2d"),
                            Colour = "#F1C453",
                            IsIncome = false,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = new Guid("f9c4d5cf-ef6e-bb5a-c7ed-73bfe297e22d"),
                            Colour = "#F29E4C",
                            IsIncome = false,
                            Name = "Utilities"
                        });
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.MachineLearning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MachineLearning");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReimbursesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecordId");

                    b.HasIndex("ReimbursesId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromRecordId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ToRecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromRecordId");

                    b.HasIndex("ToRecordId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("TransactionSibling", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiblingId")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId", "SiblingId");

                    b.HasIndex("SiblingId");

                    b.ToTable("TransactionSibling");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.BankRecord", b =>
                {
                    b.HasOne("FinanceManager.Domain.Entities.BankAccount", "BankAccount")
                        .WithMany("BankRecords")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.BudgetEntry", b =>
                {
                    b.HasOne("FinanceManager.Domain.Entities.BudgetYear", "BudgetYear")
                        .WithMany()
                        .HasForeignKey("BudgetYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetYear");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.Category", b =>
                {
                    b.HasOne("FinanceManager.Domain.Entities.CategoryGroup", "Group")
                        .WithMany("Categories")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.MachineLearning", b =>
                {
                    b.HasOne("FinanceManager.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinanceManager.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FinanceManager.Domain.Entities.BankRecord", "Record")
                        .WithMany("Transactions")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.Entities.Transaction", "Reimburses")
                        .WithMany("Reimbursements")
                        .HasForeignKey("ReimbursesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Record");

                    b.Navigation("Reimburses");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("FinanceManager.Domain.Entities.BankRecord", "FromRecord")
                        .WithMany()
                        .HasForeignKey("FromRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.Entities.BankRecord", "ToRecord")
                        .WithMany()
                        .HasForeignKey("ToRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRecord");

                    b.Navigation("ToRecord");
                });

            modelBuilder.Entity("TransactionSibling", b =>
                {
                    b.HasOne("FinanceManager.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("SiblingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.BankAccount", b =>
                {
                    b.Navigation("BankRecords");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.BankRecord", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.CategoryGroup", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("FinanceManager.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Reimbursements");
                });
#pragma warning restore 612, 618
        }
    }
}
