<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>4b6933af-1511-4944-98c3-68c1e0568c21</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Havit.Blazor.Components.Web.Bootstrap" Version="4.22.0" />
    <PackageReference Include="Havit.Blazor.Components.Web.ECharts" Version="4.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceManager.Application\FinanceManager.Application.csproj" />
    <ProjectReference Include="..\FinanceManager.Domain\FinanceManager.Domain.csproj" />
    <ProjectReference Include="..\FinanceManager.Infrastructure\FinanceManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Watch Include="..\FinanceManager.Application\**\*.cs" />
    <Watch Include="..\FinanceManager.Domain\**\*.cs" />
    <Watch Include="..\FinanceManager.Infrastructure\**\*.cs" />
  </ItemGroup>

</Project>
